# Generated by Django 3.2.9 on 2021-12-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_body_double'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body_thirth',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='body_double',
            field=models.TextField(default=''),
        ),
    ]
