# Generated by Django 3.2.9 on 2021-12-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_body_thirth_post_body_third'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_first',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d'),
        ),
    ]
