# Generated by Django 3.2.9 on 2021-12-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_image_first'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_second',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_third',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d'),
        ),
    ]
